// <auto-generated />
using System;
using Finance.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241128200642_InitDBMigration")]
    partial class InitDBMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finance.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Finance.Models.FinanceMonth", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("MonthId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.ToTable("FinanceMonths");
                });

            modelBuilder.Entity("Finance.Models.Month", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MonthOrdinal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Months");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonthOrdinal = 1,
                            Name = "January"
                        },
                        new
                        {
                            Id = 2,
                            MonthOrdinal = 2,
                            Name = "February"
                        },
                        new
                        {
                            Id = 3,
                            MonthOrdinal = 3,
                            Name = "March"
                        },
                        new
                        {
                            Id = 4,
                            MonthOrdinal = 4,
                            Name = "April"
                        },
                        new
                        {
                            Id = 5,
                            MonthOrdinal = 5,
                            Name = "May"
                        },
                        new
                        {
                            Id = 6,
                            MonthOrdinal = 6,
                            Name = "June"
                        },
                        new
                        {
                            Id = 7,
                            MonthOrdinal = 7,
                            Name = "July"
                        },
                        new
                        {
                            Id = 8,
                            MonthOrdinal = 8,
                            Name = "August"
                        },
                        new
                        {
                            Id = 9,
                            MonthOrdinal = 9,
                            Name = "September"
                        },
                        new
                        {
                            Id = 10,
                            MonthOrdinal = 10,
                            Name = "October"
                        },
                        new
                        {
                            Id = 11,
                            MonthOrdinal = 11,
                            Name = "November"
                        },
                        new
                        {
                            Id = 12,
                            MonthOrdinal = 12,
                            Name = "December"
                        });
                });

            modelBuilder.Entity("Finance.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<long>("FinanceMonthId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FinanceMonthId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Finance.Models.FinanceMonth", b =>
                {
                    b.HasOne("Finance.Models.Month", "Month")
                        .WithMany()
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Month");
                });

            modelBuilder.Entity("Finance.Models.Transaction", b =>
                {
                    b.HasOne("Finance.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finance.Models.FinanceMonth", "FinanceMonth")
                        .WithMany()
                        .HasForeignKey("FinanceMonthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FinanceMonth");
                });
#pragma warning restore 612, 618
        }
    }
}
